name: Backport pull request

on:
  pull_request:
    branches:
    - master
    types:
    - closed

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: pull-request-action
        uses: ./.github/actions/pull-request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE: ${{ github.event.pull_request.head.label }}
          TARGET: "auto-pr-target"
          BODY: "AUTO BACKPORT PR: From #${{ github.event.pull_request.number }}"
          TITLE: "BACKPORTING PR #${{ github.event.pull_request.number }}"
