name: Backport pull request

on:
  pull_request:
    branches:
    - master
    types:
    - closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: |
        git fetch "${{ github.event.pull_request.head.repo.clone_url }}" "${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}"
    - name: pull-request
      uses: ./.github/actions/pull-request
      with:
        source_branch: "${{ github.event.pull_request.head.label }}"
        destination_branch: "backport-target-3"
        pr_title: "BACKPORT: #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}"
        pr_body: ":leftwards_arrow_with_hook: **An automated backport PR**. Backporting ${{ github.event.pull_request.html_url }}."
        pr_reviewer: "${{ github.event.pull_request.merged_by.login }}"
        pr_assignee: "${{ github.event.pull_request.merged_by.login }}"
        github_token: ${{ secrets.GITHUB_TOKEN }}
