name: Backport pull request

on:
  pull_request:
    branches:
    - master
    types:
    - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check preconditions
      run: |
        echo "Validating"
        exit 1
    - name: Create pull request
      uses: repo-sync/pull-request@v2.0.1
      with:
        source_branch: "${{ github.event.pull_request.head.ref }}"
        destination_branch: "backport-target-3"
        pr_title: "[Backport]: #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}"
        pr_body: ":leftwards_arrow_with_hook: **An automated backport PR**. Backporting pull request ${{ github.event.pull_request.html_url }}."
        pr_reviewer: "${{ github.event.pull_request.merged_by.login }}"
        pr_assignee: "${{ github.event.pull_request.merged_by.login }}"
        github_token: ${{ secrets.GITHUB_TOKEN }}
