name: Backport pull request

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "master"
        destination_branch: "backport-target"
        pr_title: "Pulling ${{ github.ref }} into backport-target"
        pr_body: ":crown: *An automated PR*"
        pr_reviewer: "gcwiak"
        pr_assignee: "gcwiak"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
