name: Backport pull request

on:
  pull_request:
    branches:
    - master
    types:
    - closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
    - uses: actions/checkout@v2
     run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: pull-request
      uses: ./.github/actions/pull-request
      with:
        source_branch: "${{ github.event.pull_request.head.ref }}"
        source_repo: "${{ github.event.pull_request.head.repo.clone_url }}"
        source_owner: "${{ github.event.pull_request.head.repo.owner.login }}"
        destination_branch: "backport-target-3"
        destination_repo: "${{ github.event.pull_request.base.repo.clone_url }}"
        pr_title: "BACKPORT: #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}"
        pr_body: ":leftwards_arrow_with_hook: **An automated backport PR**. Backporting ${{ github.event.pull_request.html_url }}."
        pr_reviewer: "${{ github.event.pull_request.merged_by.login }}"
        pr_assignee: "${{ github.event.pull_request.merged_by.login }}"
        github_token: ${{ secrets.GITHUB_TOKEN }}
